version: '3.3'
services:
    web:
        image: "salasrock:5000/photosorterapi"
        container_name: photosorter
        ports:
            - "8500:80"
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
        volumes:
            - /nas/docker/photosorter/logs:/logs
            - /nas/home_content:/mnt/home_content
        restart: unless-stopped
        network_mode: bridge
