version: "3.1"

networks:
    net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
services:
  db:
    image: mariadb:latest
    container_name: piwigo_mariadb
    restart: always
    privileged: true
    volumes:
      - /nas/docker/piwigo/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: piwigodb
      MYSQL_USER: piwigo_user
      MYSQL_PASSWORD: piwigo_pass
      MYSQL_ROOT_PASSWORD: toor
    networks:
      net:
        ipv4_address: 172.28.1.1
  app:
    image: linuxserver/piwigo
    container_name: piwigo
    environment:
      - PUID=1001
      - PGID=1002
      - TZ=America/Chicago
    volumes:
      - /nas/docker/piwigo/config:/config
      - /nas/home_content/Pictures:/config/www/gallery/galleries/Pictures
    ports:
      - 8010:80
    links:
      - db
    depends_on:
      - db
    networks:
      net:
        ipv4_address: 172.28.1.2
    restart: unless-stopped
