version: '3.2'

services:
  web:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - '3333:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - /nas/docker/grafana/grafana-provisioning/:/etc/grafana/provisioning
    environment:
     # - GF_SECURITY_ADMIN_USER=admin
     # - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_SECURITY_ALLOW_EMBEDDING=true
volumes:
  grafana_data:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: /nas/docker/grafana/data
