version: '3.1'
services:
  letsencrypt: # https://github.com/linuxserver/docker-letsencrypt
    container_name: letsencrypt
    image: linuxserver/letsencrypt:latest
    restart: unless-stopped
    cap_add:
    - NET_ADMIN
    volumes:
    - /nas/docker/letsencrypt/config:/config
    - /etc/localtime:/etc/localtime:ro
    environment:
    - PGID=1002
    - PUID=1000
    - FILE__EMAIL=/run/secrets/email
    - FILE__URL=/run/secrets/duckdns_url
    - SUBDOMAINS=wildcard
    - VALIDATION=duckdns
    - TZ=America/Chicago
    - DUCKDNSTOKEN=xxxxxxxxxxxxxxxxxxx
#    - STAGING=true
    ports:
    - "80:80"
    - "443:443"
    secrets:
    - email
    - duckdns_url
    - duckdns_token
secrets:
  email:
    file: email.txt
  duckdns_url:
    file: duckdns_url.txt
  duckdns_token:
    file: duckdns_token.txt
